### ISSUE TITLE
Comparation to Google Trends

### ISSUE THREAD

**Issue by servusoft** [emmanuel-keller/github-language-statistics#2]
Google Trends rates java as a descendant
https://www.google.de/trends/explore?cat=31&q=%2Fm%2F0jgqg,%2Fm%2F07sbkfb,%2Fm%2F02p97
Strange that github has a different picture.

**Comment by M-Porter** [comment]
This project shows trends in Github, not the world or trends in google searches. So it wouldn't make sense to compare two.

**Comment by servusoft** [comment]
Generally I agree, but I think, github is big enough to compare with the world.
I think  in the calculation should be counted not the number of repositories per language, 
but how much the code lines of language. A repository may contain many languages.
This calculation could be somewhat more complex ...

**Comment by emmanuel-keller** [comment]
This is only statistics. And it should just be understood for what it is. I think It is not reliable to know if a language is trendy or not. However, it is useful to see how the usage of a language evolves. I made that because I wanted to see how the emerging languages (Swift, Rust, Go) are growing.
